version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - postgresql
    container_name: tinyurl
    ports:
      - "3020:3020"
    environment:
      - MONGO_PASSWORD=tinyurl
      - MONGO_INITDB_DATABASE=tinyurl
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: npm run setup:pg && npm run start

  mongodb:
    image: mongo
    container_name: mongo-tinyurl
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tinyurl

  postgresql:
    image: postgres
    container_name: postgres-tinyurl
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tinyurl
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
