version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - postgresql
    ports:
      - "8080:8080"
    environment:
      - MONGO_PASSWORD=tinyurl
      - MONGO_INITDB_DATABASE=tinyurl
      - POSTGRES_PASSWORD=tinyurl
      - POSTGRES_DB=tinyurl

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tinyurl

  postgresql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=tinyurl
      - POSTGRES_USER=tinyurl
      - POSTGRES_PASSWORD=tinyurl
