CREATE TABLE IF NOT EXISTS URLStats (
  id SERIAL PRIMARY KEY,
  ShortenedURL VARCHAR(255) NOT NULL,
  OriginalURL VARCHAR(255) NOT NULL,
  IPAddress VARCHAR(255) NOT NULL,
  UserAgent VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ShortenedURL (ShortenedURL),
  INDEX idx_UserID (UserID)
);
